/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.io.IOException;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;
import java.util.Map.Entry;
import java.util.Scanner;
import java.util.UUID;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

public class App {

    public static void main(String[] args) {
        System.out.println("Running Train Ticket Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        int trainSelectedForBooking = 0;

        UserBookingService userBookingService;

        try {
            userBookingService = new UserBookingService();
        } catch (Exception e) {
            System.out.println("Something went wrong. Please try again later.");
            return;
        }

        while(option != 7) {
            System.out.println("1. Signup");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Train");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel ticket");
            System.out.println("7. Exit");
            System.out.print("Enter your choice: ");
            option = scanner.nextInt();
            scanner.nextLine();

            switch(option) {
                case 2:
                    System.out.print("Enter your username: ");
                    String username = scanner.nextLine();
                    System.out.print("Enter your password: ");
                    String password = scanner.nextLine();
                    User user = new User(username, password, UserServiceUtil.hashPassword(password), UUID.randomUUID().toString(), new ArrayList<>());
                    
                    try {
                        userBookingService = new UserBookingService(user);
                        if(userBookingService.loginUser()) {
                            System.out.println("Login successful");
                        } else {
                            System.out.println("Login failed");
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    
                    break;
                case 1:
                    System.out.print("Enter your username: ");
                    String signupName = scanner.nextLine();
                    System.out.print("Enter your password: ");
                    String signupPassword = scanner.nextLine();
                    User signupUser = new User(signupName, signupPassword, UserServiceUtil.hashPassword(signupPassword), UUID.randomUUID().toString(), new ArrayList<>());
                    
                    if(userBookingService.signup(signupUser)) {
                        System.out.println("Signup successful");
                    } else {
                        System.out.println("Signup failed");
                    }
                    break;
                case 3:
                    System.out.println("Fetching booking");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.print("Enter source: ");
                    String source = scanner.nextLine();
                    System.out.print("Enter destination: ");
                    String destination = scanner.nextLine();

                    List<Train> trains = userBookingService.getTrains(source, destination);
                    int i = 1;
                    for(Train t : trains) {
                        System.out.println(i + ". TrainId: " + t.getTrainId());
                        for(Entry<String, Time> entry : t.getStationTimes().entrySet()) {
                            System.out.println("station "+entry.getKey() +" time: " + entry.getValue());
                        }
                    }

                    System.out.print("Select a train by typing 1, 2, 3, ...: ");
                    trainSelectedForBooking = scanner.nextInt();
                    break;
            }
        }
    }
}
